name: release-image-gitea

on:
  push:
    tags:
      - 0.*

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          images: ${{ vars.REPOSITORY_HOST }}/${{ gitea.repository }}

      - name: Log into Registry
        id: log-in
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.REPOSITORY_HOST }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.REPOSITORY_TOKEN }}

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          oci: true
          image: ${{ vars.REPOSITORY_HOST }}/${{ gitea.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: |
            ./Dockerfile

      - name: Push Image
        id: push-to-gitea
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ vars.REPOSITORY_HOST }}
