name: release-image-harbor

on:
  push:
    tags:
      - 0.*

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Kubeconfig
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BUILDX }}" > $HOME/.kube/config

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=gitea
            qemu.install=true

      - name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          images: ${{ vars.REGISTRY_HOST }}/images/site-profile

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile

      - name: Actions Ntfy
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.NTFY_CRED }}" \
            -H "Title: Site-Profile Image Released to Harbor: ${{ steps.meta.outputs.tags }}" \
            -H "Content-Type: text/plain" \
            -d 'Repo: ${{ gitea.repository }}\nCommit: ${{ gitea.sha }}\nRef: ${{ gitea.ref }}\nStatus: ${{ job.status}}' \
            ${{ secrets.NTFY_URL }}
